letters: letters.c letters.h
	gcc -g -ansi -Wall -pedantic letters.c -o letters
	@echo "recompiling"


run: letters
	./letters

scratchpad: scratchpad.c
	gcc -g -ansi -Wall -pedantic scratchpad.c -o scratchpad
	./scratchpad