#-------------------------------------------------------------------------------
# Author: Nathanael J Y
# Last Modified: 17/03/2021
# Written for: The Open University Of Israel
# Course: 20465 - C Programming Workshop
# Assignment: Maman 11 Question 2
#-------------------------------------------------------------------------------

my_sin: my_sin.c my_sin.h
	gcc -g -ansi -Wall -pedantic -lm my_sin.c -o my_sin

run: my_sin
	./my_sin