#-------------------------------------------------------------------------------
# Author: Nathanael J Y
# Last Modified: 16/04/2021
# Written for: The Open University Of Israel
# Course: 20465 - C Programming Workshop
# Assignment: Maman 22 Question 1
#-------------------------------------------------------------------------------

objects = set.o myset.o
debugFlags = -g -ansi -Wall -pedantic

bitmap_128: bitmap_128.c bitmap_128.h
	gcc $(debugFlags) bitmap_128.c -o bitmap_128